import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  ShieldCheck, AlertTriangle, CheckCircle2, XCircle,
  Sparkles, Download, ClipboardList,
} from 'lucide-react';
import toast from 'react-hot-toast';
import { analyze } from '../services/api';
import type { StandardResult } from '../types';

interface ComplianceResult {
  standard: StandardResult;
  status: 'required' | 'recommended' | 'optional';
  reason: string;
}

const STATUS_CONFIG = {
  required:    { label: 'Required',    color: 'text-red-400',    bg: 'bg-red-400/10 border-red-400/20',    icon: XCircle },
  recommended: { label: 'Recommended', color: 'text-yellow-400', bg: 'bg-yellow-400/10 border-yellow-400/20', icon: AlertTriangle },
  optional:    { label: 'Optional',    color: 'text-green-400',  bg: 'bg-green-400/10 border-green-400/20',  icon: CheckCircle2 },
};

function getStatus(score: number): 'required' | 'recommended' | 'optional' {
  if (score >= 75) return 'required';
  if (score >= 45) return 'recommended';
  return 'optional';
}

export default function ComplianceChecker() {
  const [product, setProduct] = useState('');
  const [company, setCompany] = useState('');
  const [results, setResults] = useState<ComplianceResult[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [generated, setGenerated] = useState(false);

  const handleCheck = async () => {
    if (!product.trim() || product.length < 10) {
      toast.error('Enter a detailed product description (min 10 chars)');
      return;
    }
    setIsLoading(true);
    setResults([]);
    setGenerated(false);
    try {
      const data = await analyze(product, 5, true);
      const mapped: ComplianceResult[] = data.results.map((r) => ({
        standard: r,
        status: getStatus(r.confidence_score),
        reason: r.rationale || r.scope.slice(0, 120) + '…',
      }));
      setResults(mapped);
      setGenerated(true);
      toast.success('Compliance report generated');
    } catch (err: any) {
      toast.error(err?.response?.data?.detail || 'API error');
    } finally {
      setIsLoading(false);
    }
  };

  const handleDownload = () => {
    const lines = [
      `BIS COMPLIANCE REPORT`,
      `Generated: ${new Date().toLocaleString()}`,
      `Company: ${company || 'N/A'}`,
      `Product: ${product}`,
      ``,
      `APPLICABLE STANDARDS`,
      `${'─'.repeat(60)}`,
      ...results.map((r) =>
        `[${r.status.toUpperCase()}] ${r.standard.standard_no} — ${r.standard.title}\n  ${r.reason}\n`
      ),
      ``,
      `Generated by BIS Antigravity AI — Tech_Bridgers`,
    ];
    const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `BIS_Compliance_Report_${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success('Report downloaded');
  };

  const required    = results.filter((r) => r.status === 'required');
  const recommended = results.filter((r) => r.status === 'recommended');
  const optional    = results.filter((r) => r.status === 'optional');

  return (
    <div className="flex-1 overflow-y-auto px-6 py-6">
      <div className="max-w-3xl mx-auto">
        {/* Header */}
        <div className="flex items-center gap-3 mb-1">
          <div className="w-9 h-9 rounded-xl bg-green-500/10 border border-green-500/20 flex items-center justify-center">
            <ShieldCheck className="w-5 h-5 text-green-400" />
          </div>
          <div>
            <h1 className="text-2xl font-bold text-white">Compliance Checker</h1>
            <p className="text-slate-500 text-sm">Generate a BIS compliance report for your product</p>
          </div>
        </div>

        {/* Input card */}
        <div className="bg-[#0d1424] border border-white/5 rounded-2xl p-5 mt-5 mb-5">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
            <div>
              <label className="block text-xs font-semibold text-slate-400 uppercase tracking-wider mb-1.5">
                Company / MSE Name (optional)
              </label>
              <input
                value={company}
                onChange={(e) => setCompany(e.target.value)}
                placeholder="e.g., Sharma Cement Works Pvt Ltd"
                className="w-full px-3 py-2.5 bg-white/5 border border-white/5 rounded-xl text-sm text-white placeholder-slate-600 focus:outline-none focus:border-blue-500/40 transition-colors"
              />
            </div>
            <div>
              <label className="block text-xs font-semibold text-slate-400 uppercase tracking-wider mb-1.5">
                Product Category
              </label>
              <select
                className="w-full px-3 py-2.5 bg-white/5 border border-white/5 rounded-xl text-sm text-slate-300 focus:outline-none focus:border-blue-500/40 transition-colors"
                onChange={(e) => setProduct((p) => p ? p : e.target.value)}
              >
                <option value="" className="bg-[#0d1424]">Select a category…</option>
                <option value="OPC 53 grade cement for high rise building construction" className="bg-[#0d1424]">Cement</option>
                <option value="TMT Fe500 steel bars for RCC structure" className="bg-[#0d1424]">Steel / Rebar</option>
                <option value="M30 ready mix concrete for bridge construction" className="bg-[#0d1424]">Concrete</option>
                <option value="20mm crushed stone coarse aggregate for concrete" className="bg-[#0d1424]">Aggregates</option>
                <option value="brick masonry mortar for load bearing wall" className="bg-[#0d1424]">Masonry</option>
              </select>
            </div>
          </div>

          <label className="block text-xs font-semibold text-slate-400 uppercase tracking-wider mb-1.5">
            Product Description *
          </label>
          <textarea
            value={product}
            onChange={(e) => setProduct(e.target.value)}
            placeholder="Describe your product in detail — material type, grade, intended use, construction type…&#10;e.g., OPC 53 grade cement manufactured for high-rise residential building construction in seismic zone III"
            rows={3}
            className="w-full px-3 py-2.5 bg-white/5 border border-white/5 rounded-xl text-sm text-white placeholder-slate-600 focus:outline-none focus:border-blue-500/40 transition-colors resize-none mb-4"
          />

          <div className="flex items-center justify-between">
            <p className="text-xs text-slate-600">AI will identify required, recommended, and optional BIS standards</p>
            <button
              onClick={handleCheck}
              disabled={isLoading}
              className="flex items-center gap-2 px-5 py-2.5 bg-gradient-to-r from-green-600 to-emerald-600 hover:from-green-500 hover:to-emerald-500 disabled:opacity-50 text-white text-sm font-bold rounded-xl transition-all"
            >
              {isLoading
                ? <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                : <ShieldCheck className="w-4 h-4" />}
              {isLoading ? 'Checking…' : 'Generate Report'}
            </button>
          </div>
        </div>

        {/* Loading */}
        <AnimatePresence>
          {isLoading && (
            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
              className="flex flex-col items-center py-12 gap-3">
              <div className="w-10 h-10 border-2 border-green-500 border-t-transparent rounded-full animate-spin" />
              <p className="text-slate-400 text-sm">Analyzing compliance requirements…</p>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Report */}
        <AnimatePresence>
          {generated && !isLoading && (
            <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }}>
              {/* Report header */}
              <div className="flex items-center justify-between mb-4">
                <div className="flex items-center gap-3">
                  <ClipboardList className="w-5 h-5 text-green-400" />
                  <div>
                    <h2 className="text-base font-bold text-white">Compliance Report</h2>
                    <p className="text-xs text-slate-500">{company || 'Your Product'} · {new Date().toLocaleDateString()}</p>
                  </div>
                </div>
                <button
                  onClick={handleDownload}
                  className="flex items-center gap-2 px-4 py-2 rounded-xl border border-white/10 text-slate-300 hover:text-white hover:border-white/20 text-xs font-medium transition-all"
                >
                  <Download className="w-3.5 h-3.5" /> Download Report
                </button>
              </div>

              {/* Summary badges */}
              <div className="grid grid-cols-3 gap-3 mb-5">
                {[
                  { label: 'Required',    count: required.length,    color: 'text-red-400',    bg: 'bg-red-400/10 border-red-400/20' },
                  { label: 'Recommended', count: recommended.length, color: 'text-yellow-400', bg: 'bg-yellow-400/10 border-yellow-400/20' },
                  { label: 'Optional',    count: optional.length,    color: 'text-green-400',  bg: 'bg-green-400/10 border-green-400/20' },
                ].map((s) => (
                  <div key={s.label} className={`p-3 rounded-xl border text-center ${s.bg}`}>
                    <p className={`text-2xl font-bold ${s.color}`}>{s.count}</p>
                    <p className={`text-xs font-bold ${s.color}`}>{s.label}</p>
                  </div>
                ))}
              </div>

              {/* Standards list */}
              <div className="space-y-3">
                {results.map((r, i) => {
                  const cfg = STATUS_CONFIG[r.status];
                  return (
                    <motion.div
                      key={r.standard.standard_no}
                      initial={{ opacity: 0, x: -12 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{ delay: i * 0.07 }}
                      className="bg-[#0d1424] border border-white/5 rounded-2xl p-4 flex gap-4"
                    >
                      <div className={`shrink-0 w-8 h-8 rounded-xl flex items-center justify-center border ${cfg.bg}`}>
                        <cfg.icon className={`w-4 h-4 ${cfg.color}`} />
                      </div>
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2 mb-1 flex-wrap">
                          <span className="font-mono text-sm font-bold text-blue-400">{r.standard.standard_no}</span>
                          <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full border ${cfg.bg} ${cfg.color}`}>
                            {cfg.label}
                          </span>
                          <span className="text-[10px] text-slate-600">{r.standard.confidence_score}% match</span>
                        </div>
                        <p className="text-sm font-semibold text-white mb-1">{r.standard.title}</p>
                        <p className="text-xs text-slate-400 leading-relaxed">{r.reason}</p>
                      </div>
                    </motion.div>
                  );
                })}
              </div>

              {/* Footer note */}
              <div className="mt-5 p-4 rounded-xl bg-blue-500/5 border border-blue-500/10 text-center">
                <p className="text-xs text-slate-500">
                  This report is AI-generated for guidance only. Consult a BIS-certified professional for official compliance certification.
                </p>
                <p className="text-[10px] text-slate-600 mt-1">Generated by BIS Antigravity AI · Tech_Bridgers · {new Date().toLocaleString()}</p>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
}
