import { useState } from 'react';
import { Download, FileText, Loader2 } from 'lucide-react';
import toast from 'react-hot-toast';
import type { AdvancedResponse } from '../types';

interface Props { data: AdvancedResponse; }

export default function ReportGenerator({ data }: Props) {
  const [generating, setGenerating] = useState(false);

  const generate = async () => {
    setGenerating(true);
    try {
      // Build plain-text report (no external PDF lib needed)
      const lines: string[] = [
        '═'.repeat(65),
        '  BIS ANTIGRAVITY AI — COMPLIANCE REPORT',
        '  Tech_Bridgers | BIS Hackathon 2026',
        '═'.repeat(65),
        '',
        `Generated   : ${new Date().toLocaleString()}`,
        `Industry    : ${data.industry.toUpperCase()}`,
        `Location    : ${data.location.toUpperCase()}`,
        `Query       : ${data.query}`,
        '',
        '─'.repeat(65),
        '  RISK SUMMARY',
        '─'.repeat(65),
        `Risk Level  : ${data.risk_summary.level}`,
        `Risk Score  : ${data.risk_summary.score}/100`,
        `Coverage    : ${data.risk_summary.coverage_pct}%`,
        `Action      : ${data.risk_summary.action}`,
        '',
        '─'.repeat(65),
        '  RECOMMENDED BIS STANDARDS',
        '─'.repeat(65),
        '',
        ...data.results.flatMap((r) => [
          `#${r.rank}  ${r.standard_no}  [${r.confidence_score}% match]`,
          `    Title    : ${r.title}`,
          `    Category : ${r.category}`,
          `    Rationale: ${r.rationale || r.scope.slice(0, 200)}`,
          '',
        ]),
        '─'.repeat(65),
        '  GAP ANALYSIS',
        '─'.repeat(65),
        '',
        `Coverage: ${data.gap_analysis.coverage_pct}%  |  Risk: ${data.gap_analysis.risk_level}`,
        `Summary : ${data.gap_analysis.summary}`,
        '',
        'COVERED STANDARDS:',
        ...(data.gap_analysis.satisfied.length
          ? data.gap_analysis.satisfied.map((s) => `  ✔  ${s.standard_no} — ${s.reason}`)
          : ['  (none identified)']),
        '',
        'MISSING STANDARDS:',
        ...(data.gap_analysis.missing.length
          ? data.gap_analysis.missing.map((m) => `  ✘  ${m.standard_no} — ${m.reason}`)
          : ['  (no gaps detected)']),
        '',
        '─'.repeat(65),
        '  COMPLIANCE CHECKLISTS',
        '─'.repeat(65),
        '',
        ...data.checklists.flatMap((cl) => [
          `${cl.standard_no}:`,
          ...cl.items.map((item) => `  □  ${item}`),
          '',
        ]),
        '─'.repeat(65),
        '  WHAT-IF ANALYSIS',
        '─'.repeat(65),
        `Modified Query: ${data.whatif_query.slice(0, 300)}...`,
        '',
        '═'.repeat(65),
        '  Generated by BIS Antigravity AI — Tech_Bridgers',
        '  For official compliance, consult a BIS-certified professional.',
        '═'.repeat(65),
      ];

      const content = lines.join('\n');
      const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `BIS_Compliance_Report_${Date.now()}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      toast.success('Report downloaded successfully');
    } catch {
      toast.error('Failed to generate report');
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div className="flex items-center justify-between p-4 bg-gradient-to-r from-blue-600/10 to-purple-600/10 border border-blue-500/15 rounded-2xl">
      <div className="flex items-center gap-3">
        <div className="w-9 h-9 rounded-xl bg-blue-500/10 border border-blue-500/20 flex items-center justify-center">
          <FileText className="w-4 h-4 text-blue-400" />
        </div>
        <div>
          <p className="text-sm font-bold text-white">Download Compliance Report</p>
          <p className="text-xs text-slate-500">
            Standards · Gap analysis · Checklists · Risk assessment
          </p>
        </div>
      </div>
      <button
        onClick={generate}
        disabled={generating}
        className="flex items-center gap-2 px-4 py-2 bg-blue-600 hover:bg-blue-500 disabled:opacity-50 text-white text-xs font-bold rounded-xl transition-all shadow-lg shadow-blue-600/20"
      >
        {generating
          ? <Loader2 className="w-3.5 h-3.5 animate-spin" />
          : <Download className="w-3.5 h-3.5" />}
        {generating ? 'Generating…' : 'Download'}
      </button>
    </div>
  );
}
